[buildPlans.iosifovich]
family = "Iosifovich"
design = ["cv58", "cv25", "cv40", "cv42", "cv13", "cv51", "cv47", "cv16", "cv61", "cv20", "cv22", "cv29", "cv63", "cv33", "cv34", "cv37", "cv38"]
upright = ["cv09", "cv05", "cv01", "cv52", "cv44", "cv48", "cv11"]
italic = ["cv08", "cv24", "cv04", "cv02", "cv53", "cv49", "cv45"]

[buildPlans.iosifovich-term]
family = "Iosifovich Terminal"
design = ["cv58", "cv25", "cv40", "cv42", "cv13", "cv51", "cv47", "cv16", "cv61", "cv20", "cv22", "cv29", "cv63", "cv33", "cv34", "cv37", "cv38"]
upright = ["cv09", "cv05", "cv01", "cv52", "cv44", "cv48", "cv11"]
italic = ["cv08", "cv24", "cv04", "cv02", "cv53", "cv49", "cv45"]

[weights.thin]
shape = 100
menu  = 100
css   = 100

[weights.extralight]
shape = 200
menu  = 200
css   = 200

[weights.light]
shape = 300
menu  = 300
css   = 300

[weights.regular]
shape = 400
menu  = 400
css   = 400

[weights.medium]
shape = 500
menu  = 500
css   = 500

[weights.semibold]
shape = 600
menu  = 600
css   = 600

[weights.bold]
shape = 700
menu  = 700
css   = 700

[weights.extrabold]
shape = 800
menu  = 800
css   = 800

[weights.heavy]
shape = 900
menu  = 900
css   = 900

# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.
[slants]
upright = "normal"
italic = "italic"